name: Update dist
on:
  push:
    branches: [main]

jobs:
  update-dist-and-release:
    name: Update dist files and release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3
      - run: yarn install
      - run: yarn build
      - uses: stefanzweifel/git-auto-commit-action@v4.11.0
        with:
          file_pattern: dist/**
          commit_message: 'chore(dist): Update dist [automated commit]'
          commit_user_name: cobraz
          commit_user_email: cobraz@users.noreply.github.com
